config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :ingredients
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'

  resources :ingredients
  resources :food_groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_group.rb
class FoodGroup < ApplicationRecord
  has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes, join_table: :recipes_ingredients
  belongs_to :food_group

  validates :name, presence: true,
      length: { minimum: 3 }, uniqueness: true, :case_sensitive => false

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients, join_table: :recipes_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_groups_controller.rb
class FoodGroupsController < ApplicationController
  def index
    @food_group = FoodGroup.all
  end

  def new
    @food_group = FoodGroup.new
  end

  def create
    @food_group = FoodGroup.new(food_group_params)

    respond_to do |format|
      if @food_group.save
        format.html { redirect_to @food_group, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @food_group }
      else
        format.html { render :new }
        format.json { render json: @food_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @food_group = FoodGroup.find(params[:id])
  end

  private

  def food_group_params
      params.require(:food_group).permit(:name)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredient = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find_or_create_by(ingredient_params)
    @recipe.ingredients << @ingredient
    @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def show
    # @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

   def index
    @recipe = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :contains_gluten, :contains_dairy, :is_vegetarian)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_groups_helper.rb
module FoodGroupsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/food_groups/_form.html.erb
<%= form_for(@food_group) do |f| %>
    <% if @food_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(food_group.errors.count, "error") %> prohibited this food_group from being saved:</h2>

          <ul>
            <% food_group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/food_groups/index.html.erb
<%= provide(:title, 'Food Groups') %>
<table class="ui celled table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Ingredients</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @food_group.each do |food_group| %>
      <tr>
        <td><%= link_to food_group.name, food_group_path(food_group.id) %></td>
        <td>
          <%= link_to 'Edit', edit_food_group_path(food_group), class: 'ui primary button' %>
          <%= link_to 'Delete', food_group, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui red button' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Food Group', new_food_group_path, class: 'ui green button' %>

app/views/food_groups/new.html.erb
<h1>New Food Group</h1>

<%= render 'form', food_group: @food_group %>

<%= link_to 'Back', food_groups_path %>

app/views/food_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_group.name %>
</p>

app/views/ingredients/index.html.erb
<%= provide(:title, 'Ingredients') %>
<table class="ui celled table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Dishes</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @ingredient.each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient.name, ingredient_path(ingredient.id) %></td>
        <td>
          <ul>
            <% ingredient.recipes.each do |recipe| %>
                <li>
                  <%= link_to recipe.name, recipe_path(recipe.id) %>
                </li>
            <% end %>
          </ul>
        </td>
        <td>
          <%= link_to 'Edit', edit_ingredient_path(ingredient), class: 'ui primary button' %>
          <%= link_to 'Delete', ingredient, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui red button' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Ingredient', new_ingredient_path, class: 'ui green button' %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<strong><%= 'Recipes that use ' + @ingredient.name + ':' %></strong>
<% @ingredient.recipes.each do |recipe| %>
    <ul>
      <li>
        <%= link_to recipe.name, recipe_path(recipe.id) %>
      </li>
    </ul>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="content">
    <div class="ui inverted top attached menu">
      <a class="item toggle button">
        <i class="sidebar icon"></i>
        Navigation
      </a>
      <div class="logo">
        <%= image_tag('foodoo_logo.png', class: 'ui image') %>
        <p>foodoo</p>
      </div>
    </div>
  </div>
</header>
<div class="banner">
  <div class="content">
    <h1 class="title">
      <%= yield :title %>
    </h1>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="ui inverted labeled icon left inline vertical sidebar menu">

  <%= link_to recipes_path, class: 'item' do %>
      <i class="cookbook icon"></i>
      Recipes
  <% end %>

  <%= link_to ingredients_path, class: 'item' do %>
      <i class="carrot icon"></i>
      Ingredients
  <% end %>

  <%= link_to food_groups_path, class: 'item' do %>
      <i class="pyramid icon"></i>
      Food Groups
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospo</title>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Special+Elite|Open+Sans:400" rel="stylesheet">

</head>

<body>
<%= render 'layouts/header' %>
<div class="ui bottom attached segment pushable">
  <%= render 'layouts/sidebar' %>
  <div class="pusher inside">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <% if @recipe.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field flex">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="form break"></div>
    <div class="field">
      <%= image_tag('icons/gluten.png') %>
      <%= f.label :contains_gluten, "Contains Gluten" %>
      <%= f.check_box :contains_gluten %>
    </div>
    <div class="field">
      <%= image_tag('icons/dairy.png') %>
      <%= f.label :contains_dairy, "Contains Dairy" %>
      <%= f.check_box :contains_dairy %>
    </div>
    <div class="field">
      <%= image_tag('icons/vegetarian.png') %>
      <%= f.label :is_vegetarian, "Vegetarian" %>
      <%= f.check_box :is_vegetarian %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<%= provide(:title, @recipe.name) %>
  <div class="recipe edit content">
    <h1>Editing Recipe</h1>
    <%= render 'form', recipe: @recipe %>
    <%= render 'recipes/partials/ingredients_listing' %>
    <h2>Add an Ingredient:</h2>
    <%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
        <!-- Validate Uniqueness & IF exists THEN add association -->
        <p>
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </p>
        <%= f.submit %>
    <% end %>

    <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
    <%= link_to 'Back', recipes_path %>
  </div>

app/views/recipes/index.html.erb
<%= provide(:title, 'Recipes') %>
<div class="content">
  <p id="notice"><%= notice %></p>

  <ul class="recipe">
    <% @recipe.order(:id).each do |recipe| %>
        <li>
          <table class="ui celled table">
            <tr>
              <td class="three wide">
                <%= image_tag('http://placehold.it/350x150', class: 'image') %>
              </td>
              <td class="four wide">
                <h1><%= recipe.name %></h1>
              </td>
              <td>
                <p><%= recipe.description %></p>
                <span class="food-warning-indicator">
                  <%= image_tag('icons/dairy.png') if recipe.contains_dairy? %>
                  <%= image_tag('icons/gluten.png') if recipe.contains_gluten? %>
                  <%= image_tag('icons/vegetarian.png') if recipe.is_vegetarian? %>
              </span>
              </td>
            </tr>
          </table>
          <!-- Extended Information -->
          <div class="information">
            <h1>Ingredients</h1>
            <ul>
              <% recipe.ingredients.each do |ingredient| %>
                  <li>
                    <%= link_to ingredient.name, ingredient_path(ingredient.id) %>
                  </li>
              <% end %>
            </ul>
            <div class="edit-options">
              <%= link_to 'Edit', edit_recipe_path(recipe), class: 'ui primary button' %>
              <%= link_to 'Delete', recipe, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui red button' %>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
  <br>
  <%= link_to 'New Recipe', new_recipe_path, class: 'ui green button new-recipe' %>
</div>

app/views/recipes/new.html.erb
<div class="recipe new content">
  <h1>New Recipe</h1>
  <%= render 'form', recipe: @recipe %>
  <%= link_to 'Back', recipes_path %>
</div>

app/views/recipes/partials/_ingredients_listing.html.erb
<h2>Ingredients:</h2>
<% @recipe.ingredients.each do |ingredient| %>
    <p>
      <%= ingredient.name %>
      <%= link_to 'Destroy', ingredient, method: :delete, data: {confirm: 'Are you sure?'}, class: 'ui red button' %>
    </p>
<% end %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<%= render 'recipes/partials/ingredients_listing' %>

<h2>Add an Ingredient:</h2>
<%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
    <!-- Validate Uniqueness & IF exists THEN add association -->
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>